apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: clusterresourceoverride.autoscaling.openshift.io
webhooks:
  - name: clusterresourceoverride.autoscaling.openshift.io
    clientConfig:
      service:
        # reach the webhook via the registered aggregated API
        namespace: default
        name: kubernetes
        path: /apis/autoscaling.openshift.io/v1/clusterresourceoverride
      caBundle: $(KUBE_CA)
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - ""
        apiVersions:
          - "v1"
        resources:
          - pods
    failurePolicy: Fail
