apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: clusterresourceoverrides.admission.autoscaling.openshift.io
  labels:
    clusterresourceoverride: "true"
webhooks:
  - name: clusterresourceoverrides.admission.autoscaling.openshift.io
    clientConfig:
      service:
        # reach the webhook via the registered aggregated API
        namespace: default
        name: kubernetes
        path: /apis/admission.autoscaling.openshift.io/v1/clusterresourceoverrides
      caBundle: $(KUBE_CA)
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - ""
        apiVersions:
          - "v1"
        resources:
          - "pods"
    failurePolicy: Fail
