apiVersion: v1
kind: Service
metadata:
  name: clusterresourceoverride
  namespace: cluster-resource-override
  labels:
    clusterresourceoverride: "true"
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: server-serving-cert
spec:
  selector:
    clusterresourceoverride: "true"
  ports:
    - port: 443
      targetPort: 8443
