apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1.autoscaling.openshift.io
spec:
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURqakNDQW5hZ0F3SUJBZ0lKQUl3b2tiNTFZYkNHTUEwR0NTcUdTSWIzRFFFQkN3VUFNRnd4Q3pBSkJnTlYKQkFZVEFuaDRNUW93Q0FZRFZRUUlEQUY0TVFvd0NBWURWUVFIREFGNE1Rb3dDQVlEVlFRS0RBRjRNUW93Q0FZRApWUVFMREFGNE1Rc3dDUVlEVlFRRERBSmpZVEVRTUE0R0NTcUdTSWIzRFFFSkFSWUJlREFlRncweE9URXdNamN5Ck1qVTFORGxhRncweU1ERXdNall5TWpVMU5EbGFNRnd4Q3pBSkJnTlZCQVlUQW5oNE1Rb3dDQVlEVlFRSURBRjQKTVFvd0NBWURWUVFIREFGNE1Rb3dDQVlEVlFRS0RBRjRNUW93Q0FZRFZRUUxEQUY0TVFzd0NRWURWUVFEREFKagpZVEVRTUE0R0NTcUdTSWIzRFFFSkFSWUJlRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DCmdnRUJBT0ZVUWRsV2pwdzZIbFZkYy9UL0J2TkplZldFeWo1eG9qVllRUzFsdW5YUStYcjJ3Ym9xWHNwYW1iMGQKNkhjS1NZL0FVcnd3OUk3R3hDbG9pWDFsdWloRFZuL1FiZHVwYTc3YXBDSGhqWHpWMVg2dTlVTVozOVFNMG9TVApBem5JVHNCVTlVcUtzT0NlenI2QmN3L1V2bnlmUmVkSXkzeFFLSHo1SEQ4eDkrRHdSRTJuSGJuMlVBWFNQYXJoCjhoak5ibmtma3dKaTdDbndYS09UQ1pUbnpvVytDUy9RaXRoT1FVaWtaY2ZvenJ2WjNJZGl6UE9EUlFreGs5S0UKZjBYK05JU1lUallVVUtNblNkZW5JTHY1b2tvT0V6K25oUlFFd1Y4cU1GV1ZjeVFjbTUrY0JRRzhtSFJPSTk1Qgp5YTZyT05PVWVZSHBiS2tQOWxYVHdaQWtScE1DQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkdSZlNLKy9CaUVvCjNQdVo5Z3dyUDhubDNoTnhNQjhHQTFVZEl3UVlNQmFBRkdSZlNLKy9CaUVvM1B1Wjlnd3JQOG5sM2hOeE1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTklPbFIrRG5YWTdRSWhaRUprWgpWYlVRaE56VmxTbnpmcE5lMkhzRHVHb1VDRkhjSmIvMWJrYjROdTJxeEM2WTQ2bkVUWXB3blFQajJxVGhzTStsCjIrWEFJNXNPUllkTmVvanZmOVl3cngvNjMrWlBpYkNWR3pBM1JyWVhWT1hDN3ZXN3czRTFrMnFScmI5eDRlaFMKK3JISE02VTNXMmlzNklhOExEckkzdTlhZS84eVNZWGR5c0hTVTREM2ltQm9PelduTlVaVWNrTDhKai83aWZNWgpGYXo1Y3RQeEtFL3JBR3MrTGFkaktWT280MFUwZXcyNks5YVFoV3Z4bms4REQ0TTlZZ1JVYW1NanRneUFyRUZnCkpYUHdEdTZXampQR1ZtbTR4R0NwTVdTSkxYMHhSekdqRkJOUXpMMkQyRHBsb0NVNkppRXhQY2tUMElrSG91NkoKUzRBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  group: autoscaling.openshift.io
  groupPriorityMinimum: 1000
  service:
    name: clusterresourceoverride
    namespace: cluster-resource-override
  version: v1
  versionPriority: 15
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    clusterresourceoverride: "true"
  name: clusterresourceoverride.autoscaling.openshift.io
webhooks:
  - clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRFNU1ERXhOREl4TlRNd09Gb1hEVEk1TURFeE1qSXhOVE13T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTEViCnFqRXNvaHA1eHUrZUlONEk2K2l6eE1BMmFZYWNwYktDNGwwN1loVGpkRDU4aGoxcGhGWHpIaUpIbFJNcHVwemwKSXBQWDNsczBVRU9udzdBY2YyZFFUa3RoLzIvUy9lU05zMlJpNE90TzVsS0NtOGE4dWs0Mk1DQ1Y2UEtNQzBkVAppYWZ4Q0pwQVF5QldjS2JRME0rRDZYWHdJSk9aMzM3dGo0QjVqei9wT2o3dzB5Zk14RnBZRnUwR1N6aThmVURvCnREaFA4Ty9YaFovZElobE1yOVZWLzg3Tmh1U2Vqa0xtMTlDNFdwL09GM1JHUkMvQTFCQVhmTnVFUzR3eDFKRU8KM3FqNFNyNVF3ZlFrQWl5d29wd2kxemoxdnVWeTZIeURWWWJnd0U5OWo5V3YxT3UxOERKekloVmZWajFxMmdDWApmMEFtUjVkamNMSGtSRVlEaWJVQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBYWRGZ2kzelNlWGh6Q0VWMVc2aWlnS0NJKzlsOW14REhKYURlZkFBaWppZUo3amo0Qgo2Z2E0YlRaNDh5Vk03bE01WUpNTm1MdnR5R0hiODRCT3kxaTRBSytLcWRVM3BRdEVXN0lsa05ady9tWFFrM2RMCkVkcHlyeUJmakwvT0VveS9sYzRMR2hxQUVySHFyR2xMd1hZM1c5S1k1V2V3Z2IvT0lBMFlPd1dQUFNLNUxlT2EKY2pjenc1R1BHbjk0c2VkVStwNFZPQmRJZkFibUNuR1I5Zjd4TGxmV0d0eHFnbEFieGlXcG1Vd2d0N3BtU0lpbQpUWHNZRWNNd004djk0dXRUZ2hSUzd5NTZyb0U0Z3E3a0hxbzN0OHMzRFR1cmZBQkVVTWdvd3IzQ2FCVU1xWHNvCkxnZTRCTlpjSFc0VkY3RUtIQ1R1MHRsYzBsTlhoWTlFdjVxKwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: kubernetes
        namespace: default
        path: /apis/autoscaling.openshift.io/v1/clusterresourceoverride
    failurePolicy: Fail
    name: clusterresourceoverride.autoscaling.openshift.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods
