apiVersion: v1
kind: Namespace
metadata:
  name: cluster-resource-override
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clusterresourceoverride
  namespace: cluster-resource-override
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: should-be-default-for-aggregated-apiserver
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: system:clusterresourceoverride-requester
rules:
  - apiGroups:
      - autoscaling.openshift.io
    resources:
      - clusterresourceoverride
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: extension-server-authentication-reader-clusterresourceoverride
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: clusterresourceoverride
    namespace: cluster-resource-override
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: auth-delegator-cluster-resource-override
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
  - kind: ServiceAccount
    name: clusterresourceoverride
    namespace: cluster-resource-override
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: should-be-default-for-aggregated-apiserver
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: should-be-default-for-aggregated-apiserver
subjects:
  - kind: ServiceAccount
    name: clusterresourceoverride
    namespace: cluster-resource-override
---
apiVersion: v1
data:
  kubeCa: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRFNU1ERXhOREl4TlRNd09Gb1hEVEk1TURFeE1qSXhOVE13T0Zvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTEViCnFqRXNvaHA1eHUrZUlONEk2K2l6eE1BMmFZYWNwYktDNGwwN1loVGpkRDU4aGoxcGhGWHpIaUpIbFJNcHVwemwKSXBQWDNsczBVRU9udzdBY2YyZFFUa3RoLzIvUy9lU05zMlJpNE90TzVsS0NtOGE4dWs0Mk1DQ1Y2UEtNQzBkVAppYWZ4Q0pwQVF5QldjS2JRME0rRDZYWHdJSk9aMzM3dGo0QjVqei9wT2o3dzB5Zk14RnBZRnUwR1N6aThmVURvCnREaFA4Ty9YaFovZElobE1yOVZWLzg3Tmh1U2Vqa0xtMTlDNFdwL09GM1JHUkMvQTFCQVhmTnVFUzR3eDFKRU8KM3FqNFNyNVF3ZlFrQWl5d29wd2kxemoxdnVWeTZIeURWWWJnd0U5OWo5V3YxT3UxOERKekloVmZWajFxMmdDWApmMEFtUjVkamNMSGtSRVlEaWJVQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBYWRGZ2kzelNlWGh6Q0VWMVc2aWlnS0NJKzlsOW14REhKYURlZkFBaWppZUo3amo0Qgo2Z2E0YlRaNDh5Vk03bE01WUpNTm1MdnR5R0hiODRCT3kxaTRBSytLcWRVM3BRdEVXN0lsa05ady9tWFFrM2RMCkVkcHlyeUJmakwvT0VveS9sYzRMR2hxQUVySHFyR2xMd1hZM1c5S1k1V2V3Z2IvT0lBMFlPd1dQUFNLNUxlT2EKY2pjenc1R1BHbjk0c2VkVStwNFZPQmRJZkFibUNuR1I5Zjd4TGxmV0d0eHFnbEFieGlXcG1Vd2d0N3BtU0lpbQpUWHNZRWNNd004djk0dXRUZ2hSUzd5NTZyb0U0Z3E3a0hxbzN0OHMzRFR1cmZBQkVVTWdvd3IzQ2FCVU1xWHNvCkxnZTRCTlpjSFc0VkY3RUtIQ1R1MHRsYzBsTlhoWTlFdjVxKwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  serviceServingCertCa: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURqakNDQW5hZ0F3SUJBZ0lKQUl3b2tiNTFZYkNHTUEwR0NTcUdTSWIzRFFFQkN3VUFNRnd4Q3pBSkJnTlYKQkFZVEFuaDRNUW93Q0FZRFZRUUlEQUY0TVFvd0NBWURWUVFIREFGNE1Rb3dDQVlEVlFRS0RBRjRNUW93Q0FZRApWUVFMREFGNE1Rc3dDUVlEVlFRRERBSmpZVEVRTUE0R0NTcUdTSWIzRFFFSkFSWUJlREFlRncweE9URXdNamN5Ck1qVTFORGxhRncweU1ERXdNall5TWpVMU5EbGFNRnd4Q3pBSkJnTlZCQVlUQW5oNE1Rb3dDQVlEVlFRSURBRjQKTVFvd0NBWURWUVFIREFGNE1Rb3dDQVlEVlFRS0RBRjRNUW93Q0FZRFZRUUxEQUY0TVFzd0NRWURWUVFEREFKagpZVEVRTUE0R0NTcUdTSWIzRFFFSkFSWUJlRENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DCmdnRUJBT0ZVUWRsV2pwdzZIbFZkYy9UL0J2TkplZldFeWo1eG9qVllRUzFsdW5YUStYcjJ3Ym9xWHNwYW1iMGQKNkhjS1NZL0FVcnd3OUk3R3hDbG9pWDFsdWloRFZuL1FiZHVwYTc3YXBDSGhqWHpWMVg2dTlVTVozOVFNMG9TVApBem5JVHNCVTlVcUtzT0NlenI2QmN3L1V2bnlmUmVkSXkzeFFLSHo1SEQ4eDkrRHdSRTJuSGJuMlVBWFNQYXJoCjhoak5ibmtma3dKaTdDbndYS09UQ1pUbnpvVytDUy9RaXRoT1FVaWtaY2ZvenJ2WjNJZGl6UE9EUlFreGs5S0UKZjBYK05JU1lUallVVUtNblNkZW5JTHY1b2tvT0V6K25oUlFFd1Y4cU1GV1ZjeVFjbTUrY0JRRzhtSFJPSTk1Qgp5YTZyT05PVWVZSHBiS2tQOWxYVHdaQWtScE1DQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkdSZlNLKy9CaUVvCjNQdVo5Z3dyUDhubDNoTnhNQjhHQTFVZEl3UVlNQmFBRkdSZlNLKy9CaUVvM1B1Wjlnd3JQOG5sM2hOeE1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBTklPbFIrRG5YWTdRSWhaRUprWgpWYlVRaE56VmxTbnpmcE5lMkhzRHVHb1VDRkhjSmIvMWJrYjROdTJxeEM2WTQ2bkVUWXB3blFQajJxVGhzTStsCjIrWEFJNXNPUllkTmVvanZmOVl3cngvNjMrWlBpYkNWR3pBM1JyWVhWT1hDN3ZXN3czRTFrMnFScmI5eDRlaFMKK3JISE02VTNXMmlzNklhOExEckkzdTlhZS84eVNZWGR5c0hTVTREM2ltQm9PelduTlVaVWNrTDhKai83aWZNWgpGYXo1Y3RQeEtFL3JBR3MrTGFkaktWT280MFUwZXcyNks5YVFoV3Z4bms4REQ0TTlZZ1JVYW1NanRneUFyRUZnCkpYUHdEdTZXampQR1ZtbTR4R0NwTVdTSkxYMHhSekdqRkJOUXpMMkQyRHBsb0NVNkppRXhQY2tUMElrSG91NkoKUzRBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tlsServingCert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ0ekNDQXN1Z0F3SUJBZ0lVRkE1ZmErbkRsR2lidkMvY2M3bjBuS1Z5b1Iwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1hERUxNQWtHQTFVRUJoTUNlSGd4Q2pBSUJnTlZCQWdNQVhneENqQUlCZ05WQkFjTUFYZ3hDakFJQmdOVgpCQW9NQVhneENqQUlCZ05WQkFzTUFYZ3hDekFKQmdOVkJBTU1BbU5oTVJBd0RnWUpLb1pJaHZjTkFRa0JGZ0Y0Ck1CNFhEVEU1TVRBeU56SXlOVEV3TUZvWERUSTBNVEF5TlRJeU5URXdNRm93UURFK01Ed0dBMVVFQXhNMVkyeDEKYzNSbGNuSmxjMjkxY21ObGIzWmxjbkpwWkdVdVkyeDFjM1JsY2kxeVpYTnZkWEpqWlMxdmRtVnljbWxrWlM1egpkbU13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3BHTHZJTFMzWXdkdVdRY0VnCkxHWktqUldwaGhiQUl5dFViY2JnNy8yZERKZGYvbFl3dnc1dWJBdXBrSmkwWGEwMTlPT0d4L2d3S0RaU1MrZmQKcXduOUFlUXFOdE0ra2x3VlFqTVFhUnN6SHdjd0twMGFkbWxEbEQ2elpnYUorQTZTcFdTbzBpa0ZMSnhhbFdsYQpkVHdhWG5ueFU1TXh6Z0JDaThCSmR3aWNkdEt0dnA5Y3pVeGlyZWxRV2IydExQSGR6b0NJQVJYUGtFWmxSRnlqCmFhK3hOYnh3SGZDR2o1MnpUeGswRFdSTjUzaStzVzFVeDhnOUE4eExuUU9mbXlGU0YrakZrTkNaMDRWNURlTU8KL1kyeVJyRy9CTDlyMVVQWXZHSFJjeEhXZTlDc3dxajBYZDM2Y1hqSXFIcFM3RDhUZU5HakxVQi9aendncjRadAppUW9SQWdNQkFBR2pnYmd3Z2JVd0RnWURWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGCkJ3TUJNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRUZKQzd6ZUdOckdBdzZ2bDkvSW92T3o1MkRKMWsKTUI4R0ExVWRJd1FZTUJhQUZHUmZTSysvQmlFbzNQdVo5Z3dyUDhubDNoTnhNRUFHQTFVZEVRUTVNRGVDTldOcwpkWE4wWlhKeVpYTnZkWEpqWlc5MlpYSnlhV1JsTG1Oc2RYTjBaWEl0Y21WemIzVnlZMlV0YjNabGNuSnBaR1V1CmMzWmpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFrYWVxVGNGeEdVYUFpRXZyNkJCOHBlUGVZQVFXVEZ2cUMKamxvaFlCaWQ3R3d5SkxJWXZDczZYd2x3SjZzamtCem5EUlo5ZjZ0STZJT05EdjVJdDB0b3VzUlRrd1ZKWWFDSQpyVXV0d0dwT21KbHVIOFQvcGZYSHdRQUttSzY5MlUvWVRRMVBxQjFrblpSRlZKUjl3a2xBd1RjNGNKZllrQmpSCnFuU29oYWlCYzlrMHRyQkpxTGEvczAzRHFIeklqZ0ZNQUQ4MzM5NGJMY0dBYkkxYy9NaG1IVmxLakdQMWppSTkKbC9QUnBCWU13aE9HVWpVbURkQ0tpUWlJbWVEd093RzlYa2RtWnRoelBobkNBMXJZYWJhSXBMeU1mSHpIL2tlVQpFb3RObTVQclNlYndIa3V4TW05N25rUGtEa1U1bnhSS1lvRUE0Wm41RE5aR0RhZ3FVUlg5Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tlsServingKey: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcVJpN3lDMHQyTUhibGtIQklDeG1TbzBWcVlZV3dDTXJWRzNHNE8vOW5ReVhYLzVXCk1MOE9ibXdMcVpDWXRGMnROZlRqaHNmNE1DZzJVa3ZuM2FzSi9RSGtLamJUUHBKY0ZVSXpFR2tiTXg4SE1DcWQKR25acFE1UStzMllHaWZnT2txVmtxTklwQlN5Y1dwVnBXblU4R2w1NThWT1RNYzRBUW92QVNYY0luSGJTcmI2ZgpYTTFNWXEzcFVGbTlyU3p4M2M2QWlBRVZ6NUJHWlVSY28ybXZzVFc4Y0Izd2hvK2RzMDhaTkExa1RlZDR2ckZ0ClZNZklQUVBNUzUwRG41c2hVaGZveFpEUW1kT0ZlUTNqRHYyTnNrYXh2d1MvYTlWRDJMeGgwWE1SMW52UXJNS28KOUYzZCtuRjR5S2g2VXV3L0UzalJveTFBZjJjOElLK0diWWtLRVFJREFRQUJBb0lCQUM4UW5FdVdENW15TTIwNQo5Z2YvYzZVeWFhSWFtVUIzU1hzaFp1WjZ4Y3N0a3dCNzZQOStYZ1RyKzc4QmFROWl0M0E2TGczNG9LSyt2b2ZmCmFyVHZBME94Z0JFajIxNGlISkVxTU01VGd1ZVNya3lBditONnE4Zk1manN1bllsUFNyY1VZOVQ5VWIrSDhDamkKUjBXUE5lQmRCWEhmQWl3dG16THFkT1c5eE43UFcrT05IbWUwOUxQbFYrRlR3TVZJTURpbUFxN0R5R0FPcHRVUgpITk5SaXdlb05jbE0wSm5NV1ZkZmZCbnlMdXhzdUlRdThuM3VIR1lnYmhWMEFLc09KbTVYTEVpVG14YythYzNnCjdVRlE4dEgyV3BuT0lIaG4yR0doUGVtTGZTUklsQm80clg3YkR4Zkp5UVBBQTZzVTlhTU5FK1IzcEdIUzFWcWsKVW8wdHhyVUNnWUVBMS9tc1RqQnA2NlRNYlNER3h2Ty9NTS8zLytLS3VjSGJaZGJ3alk1Q2RTeFlBeTFRK3BTegp5SWZxdm1WcS9KQitpYU5uV3RTOW5LMzU0c0NLYS9ZNGNsaEZzQnArY05icFRhOHVsOUxZbUlOaFVHY0VqK1RRCjZycjlTT1ZaR3NhRHAvUnI3Q2tpUW5YbUo1UmExc0wzZk9MU1RlRUl6aDBOcTMxVW00UGs3V01DZ1lFQXlHOEoKWUxuU0xFL0VVeTZqa0tOaG9xd0xJLzZ6TmQ1UDhhUENNTG8wcDVBWEZ2bVcxTzFzc1daaGRQMDViaXhRWnlFaQptU2xCejhWZU13NkF0OUEvd21EaGQ4aTZVOUgrcHJZekxOVk1TMFZjemV6UGQvcW54RWFNcmJCazBJTm4weUNvCnM2MlpQc1JmdmxCSmpJOEkrTSs3dzNBK24zaEw2RGc0d1dESnJ2c0NnWUVBdUk4L1UwSEVBZjYrUXJNenFtZzUKQmJseXNGUWpRRUlNL3FZQ3dyVEN6ZWFxLzJ3R08xdy9saW12ekN4V2xLWFZ2RURLM2EvV3FNRnpQUFpVVTVZQQovcFc0VjVrTVc5a0xYYnRLRWF1NE0veHhlSWZRT2piSzRRd1J6ZTFQaTdZQVk5SlhOMlNmUmpRQ0RlaVZCOWxzCkxHaVlWcnpyRFZkK2l3RjYvN3BpTXdrQ2dZQmlNWnZMaWwzQUhiZ1Y5SFJuaU5OdGFaSHZxWGxNdThRNG9yeWgKT0toUkt4TlV5eVFzM3NCd1RMTVVLSGE1VmZaeC85YSthR3I0aWozekQzamFGS2tYNW5TdlJXU2JhZmF5My9KRQpWWjhTQlVKSkZHb3o0bFhNbjYrTjdDd0h4MGpYTTFuUzVRcDlxS0VyVUpRbnkyOWV6ZzZ6MmNxa1A4QVlYV3JZCnVqMDBmd0tCZ0RPTEpwczhqOE5YVktPc3pmTXJUVjI0dGQ3M291K1FrazdxaFljZUNzNFhoUTBIVTFuV0dydSsKejQzdGN3MUFRSVhSVzhEcUFGRHltTXBpM2xZN2NWOEl2bmtrSUo4V0hWVjlNbllYZ2g2aDBkcVJ6bGNMcTBTWgo1c0ZDOFMrSkpzM1BzWEtwUkx2emw5VDkwMnY5eThmbTNmd1Z4NFluSGZyc1EvNjM2dVRaCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: ConfigMap
metadata:
  name: certs
  namespace: default
---
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ0ekNDQXN1Z0F3SUJBZ0lVRkE1ZmErbkRsR2lidkMvY2M3bjBuS1Z5b1Iwd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1hERUxNQWtHQTFVRUJoTUNlSGd4Q2pBSUJnTlZCQWdNQVhneENqQUlCZ05WQkFjTUFYZ3hDakFJQmdOVgpCQW9NQVhneENqQUlCZ05WQkFzTUFYZ3hDekFKQmdOVkJBTU1BbU5oTVJBd0RnWUpLb1pJaHZjTkFRa0JGZ0Y0Ck1CNFhEVEU1TVRBeU56SXlOVEV3TUZvWERUSTBNVEF5TlRJeU5URXdNRm93UURFK01Ed0dBMVVFQXhNMVkyeDEKYzNSbGNuSmxjMjkxY21ObGIzWmxjbkpwWkdVdVkyeDFjM1JsY2kxeVpYTnZkWEpqWlMxdmRtVnljbWxrWlM1egpkbU13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ3BHTHZJTFMzWXdkdVdRY0VnCkxHWktqUldwaGhiQUl5dFViY2JnNy8yZERKZGYvbFl3dnc1dWJBdXBrSmkwWGEwMTlPT0d4L2d3S0RaU1MrZmQKcXduOUFlUXFOdE0ra2x3VlFqTVFhUnN6SHdjd0twMGFkbWxEbEQ2elpnYUorQTZTcFdTbzBpa0ZMSnhhbFdsYQpkVHdhWG5ueFU1TXh6Z0JDaThCSmR3aWNkdEt0dnA5Y3pVeGlyZWxRV2IydExQSGR6b0NJQVJYUGtFWmxSRnlqCmFhK3hOYnh3SGZDR2o1MnpUeGswRFdSTjUzaStzVzFVeDhnOUE4eExuUU9mbXlGU0YrakZrTkNaMDRWNURlTU8KL1kyeVJyRy9CTDlyMVVQWXZHSFJjeEhXZTlDc3dxajBYZDM2Y1hqSXFIcFM3RDhUZU5HakxVQi9aendncjRadAppUW9SQWdNQkFBR2pnYmd3Z2JVd0RnWURWUjBQQVFIL0JBUURBZ1dnTUJNR0ExVWRKUVFNTUFvR0NDc0dBUVVGCkJ3TUJNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRUZKQzd6ZUdOckdBdzZ2bDkvSW92T3o1MkRKMWsKTUI4R0ExVWRJd1FZTUJhQUZHUmZTSysvQmlFbzNQdVo5Z3dyUDhubDNoTnhNRUFHQTFVZEVRUTVNRGVDTldOcwpkWE4wWlhKeVpYTnZkWEpqWlc5MlpYSnlhV1JsTG1Oc2RYTjBaWEl0Y21WemIzVnlZMlV0YjNabGNuSnBaR1V1CmMzWmpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUFrYWVxVGNGeEdVYUFpRXZyNkJCOHBlUGVZQVFXVEZ2cUMKamxvaFlCaWQ3R3d5SkxJWXZDczZYd2x3SjZzamtCem5EUlo5ZjZ0STZJT05EdjVJdDB0b3VzUlRrd1ZKWWFDSQpyVXV0d0dwT21KbHVIOFQvcGZYSHdRQUttSzY5MlUvWVRRMVBxQjFrblpSRlZKUjl3a2xBd1RjNGNKZllrQmpSCnFuU29oYWlCYzlrMHRyQkpxTGEvczAzRHFIeklqZ0ZNQUQ4MzM5NGJMY0dBYkkxYy9NaG1IVmxLakdQMWppSTkKbC9QUnBCWU13aE9HVWpVbURkQ0tpUWlJbWVEd093RzlYa2RtWnRoelBobkNBMXJZYWJhSXBMeU1mSHpIL2tlVQpFb3RObTVQclNlYndIa3V4TW05N25rUGtEa1U1bnhSS1lvRUE0Wm41RE5aR0RhZ3FVUlg5Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBcVJpN3lDMHQyTUhibGtIQklDeG1TbzBWcVlZV3dDTXJWRzNHNE8vOW5ReVhYLzVXCk1MOE9ibXdMcVpDWXRGMnROZlRqaHNmNE1DZzJVa3ZuM2FzSi9RSGtLamJUUHBKY0ZVSXpFR2tiTXg4SE1DcWQKR25acFE1UStzMllHaWZnT2txVmtxTklwQlN5Y1dwVnBXblU4R2w1NThWT1RNYzRBUW92QVNYY0luSGJTcmI2ZgpYTTFNWXEzcFVGbTlyU3p4M2M2QWlBRVZ6NUJHWlVSY28ybXZzVFc4Y0Izd2hvK2RzMDhaTkExa1RlZDR2ckZ0ClZNZklQUVBNUzUwRG41c2hVaGZveFpEUW1kT0ZlUTNqRHYyTnNrYXh2d1MvYTlWRDJMeGgwWE1SMW52UXJNS28KOUYzZCtuRjR5S2g2VXV3L0UzalJveTFBZjJjOElLK0diWWtLRVFJREFRQUJBb0lCQUM4UW5FdVdENW15TTIwNQo5Z2YvYzZVeWFhSWFtVUIzU1hzaFp1WjZ4Y3N0a3dCNzZQOStYZ1RyKzc4QmFROWl0M0E2TGczNG9LSyt2b2ZmCmFyVHZBME94Z0JFajIxNGlISkVxTU01VGd1ZVNya3lBditONnE4Zk1manN1bllsUFNyY1VZOVQ5VWIrSDhDamkKUjBXUE5lQmRCWEhmQWl3dG16THFkT1c5eE43UFcrT05IbWUwOUxQbFYrRlR3TVZJTURpbUFxN0R5R0FPcHRVUgpITk5SaXdlb05jbE0wSm5NV1ZkZmZCbnlMdXhzdUlRdThuM3VIR1lnYmhWMEFLc09KbTVYTEVpVG14YythYzNnCjdVRlE4dEgyV3BuT0lIaG4yR0doUGVtTGZTUklsQm80clg3YkR4Zkp5UVBBQTZzVTlhTU5FK1IzcEdIUzFWcWsKVW8wdHhyVUNnWUVBMS9tc1RqQnA2NlRNYlNER3h2Ty9NTS8zLytLS3VjSGJaZGJ3alk1Q2RTeFlBeTFRK3BTegp5SWZxdm1WcS9KQitpYU5uV3RTOW5LMzU0c0NLYS9ZNGNsaEZzQnArY05icFRhOHVsOUxZbUlOaFVHY0VqK1RRCjZycjlTT1ZaR3NhRHAvUnI3Q2tpUW5YbUo1UmExc0wzZk9MU1RlRUl6aDBOcTMxVW00UGs3V01DZ1lFQXlHOEoKWUxuU0xFL0VVeTZqa0tOaG9xd0xJLzZ6TmQ1UDhhUENNTG8wcDVBWEZ2bVcxTzFzc1daaGRQMDViaXhRWnlFaQptU2xCejhWZU13NkF0OUEvd21EaGQ4aTZVOUgrcHJZekxOVk1TMFZjemV6UGQvcW54RWFNcmJCazBJTm4weUNvCnM2MlpQc1JmdmxCSmpJOEkrTSs3dzNBK24zaEw2RGc0d1dESnJ2c0NnWUVBdUk4L1UwSEVBZjYrUXJNenFtZzUKQmJseXNGUWpRRUlNL3FZQ3dyVEN6ZWFxLzJ3R08xdy9saW12ekN4V2xLWFZ2RURLM2EvV3FNRnpQUFpVVTVZQQovcFc0VjVrTVc5a0xYYnRLRWF1NE0veHhlSWZRT2piSzRRd1J6ZTFQaTdZQVk5SlhOMlNmUmpRQ0RlaVZCOWxzCkxHaVlWcnpyRFZkK2l3RjYvN3BpTXdrQ2dZQmlNWnZMaWwzQUhiZ1Y5SFJuaU5OdGFaSHZxWGxNdThRNG9yeWgKT0toUkt4TlV5eVFzM3NCd1RMTVVLSGE1VmZaeC85YSthR3I0aWozekQzamFGS2tYNW5TdlJXU2JhZmF5My9KRQpWWjhTQlVKSkZHb3o0bFhNbjYrTjdDd0h4MGpYTTFuUzVRcDlxS0VyVUpRbnkyOWV6ZzZ6MmNxa1A4QVlYV3JZCnVqMDBmd0tCZ0RPTEpwczhqOE5YVktPc3pmTXJUVjI0dGQ3M291K1FrazdxaFljZUNzNFhoUTBIVTFuV0dydSsKejQzdGN3MUFRSVhSVzhEcUFGRHltTXBpM2xZN2NWOEl2bmtrSUo4V0hWVjlNbllYZ2g2aDBkcVJ6bGNMcTBTWgo1c0ZDOFMrSkpzM1BzWEtwUkx2emw5VDkwMnY5eThmbTNmd1Z4NFluSGZyc1EvNjM2dVRaCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
kind: Secret
metadata:
  name: server-serving-cert
  namespace: cluster-resource-override
type: kubernetes.io/tls
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: server-serving-cert
  labels:
    clusterresourceoverride: "true"
  name: clusterresourceoverride
  namespace: cluster-resource-override
spec:
  ports:
    - port: 443
      targetPort: 8443
  selector:
    clusterresourceoverride: "true"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    clusterresourceoverride: "true"
  name: clusterresourceoverride
  namespace: cluster-resource-override
spec:
  replicas: 1
  selector:
    matchLabels:
      clusterresourceoverride: "true"
  template:
    metadata:
      labels:
        clusterresourceoverride: "true"
      name: clusterresourceoverride
    spec:
      containers:
        - args:
            - --secure-port=8443
            - --audit-log-path=-
            - --tls-cert-file=/var/serving-cert/tls.crt
            - --tls-private-key-file=/var/serving-cert/tls.key
            - --v=8
          image: docker.io/tohinkashem/clusterresourceoverride:dev
          imagePullPolicy: Always
          name: clusterresourceoverride
          ports:
            - containerPort: 8443
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
          volumeMounts:
            - mountPath: /var/serving-cert
              name: serving-cert
      serviceAccountName: clusterresourceoverride
      volumes:
        - name: serving-cert
          secret:
            defaultMode: 420
            secretName: server-serving-cert

