FROM centos:7

ADD artifacts/configuration.yaml /etc/clusterresourceoverride/config/override.yaml
ADD bin/cluster-resource-override-admission /usr/bin

ENV CONFIGURATION_PATH=/etc/clusterresourceoverride/config/override.yaml

ENTRYPOINT ["/usr/bin/cluster-resource-override-admission"]
