FROM registry.access.redhat.com/ubi9-minimal:9.6

ADD artifacts/configuration.yaml /etc/clusterresourceoverride/config/override.yaml
ADD bin/cluster-resource-override-admission /usr/bin

ENV CONFIGURATION_PATH=/etc/clusterresourceoverride/config/override.yaml

