apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: cluster-resource-override
  name: svtoverride
  labels:
    svtoverride: "true"
spec:
  selector:
    matchLabels:
      svtoverride: "true"
  template:
    metadata:
      name: svtoverride
      labels:
        svtoverride: "true"
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ''
      hostNetwork: true
      serviceAccountName: clusterresourceoverride
      containers:
        - name: svtoverride
          image: docker.io/tohinkashem/clusterresourceoverride:dev
          imagePullPolicy: Always
          command:
            - /usr/bin/selinux-fix-admission
          args:
            - "--secure-port=9401"
            - "--bind-address=127.0.0.1"
            - "--tls-cert-file=/var/serving-cert/tls.crt"
            - "--tls-private-key-file=/var/serving-cert/tls.key"
            - "--v=8"
          ports:
            - containerPort: 9401
              hostPort: 9401
              protocol: TCP
          volumeMounts:
            - mountPath: /var/serving-cert
              name: serving-cert
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9401
              scheme: HTTPS
      volumes:
        - name: serving-cert
          secret:
            defaultMode: 420
            secretName: server-serving-cert
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 120
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 120
