apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: podsvtoverride.admission.node.openshift.io
  labels:
    clusterresourceoverride: "true"
webhooks:
  - name: podsvtoverride.admission.node.openshift.io
    namespaceSelector:
      matchLabels:
        podsvtoverride.admission.node.openshift.io/enabled: "true"
      matchExpressions:
        - key: runlevel
          operator: NotIn
          values: ["0","1"]
    matchPolicy: Equivalent
    clientConfig:
      url: https://localhost:9401/apis/admission.node.openshift.io/v1/podsvtoverride
      caBundle: SERVICE_SERVING_CERT_CA
    rules:
      - operations:
          - CREATE
          - UPDATE
        apiGroups:
          - ""
        apiVersions:
          - "v1"
        resources:
          - "pods"
        scope: "Namespaced"
    failurePolicy: Fail
    timeoutSeconds: 5
    sideEffects: None
    reinvocationPolicy: IfNeeded
    admissionReviewVersions:
      - "v1"
