apiVersion: admission.k8s.io/v1
kind: AdmissionReview
request:
  kind:
    group:
    kind: Pod
    version: v1
  resource:
    group:
    version: v1
    resource: pods
  object:
    metadata:
      name: myapp
    spec:
      containers:
        - image: nginx
          name: nginx-frontend
        - image: mysql
          name: mysql-backend
