varReference:
  - path: subjects/namespace
    kind: ClusterRoleBinding
  - path: subjects/namespace
    kind: RoleBinding
  - path: metadata.namespace
    kind: Deployment
  - path: metadata.namespace
    kind: ServiceAccount
  - path: metadata.namespace
    kind: Secret
  - path: metadata.namespace
    kind: Service
  - path: spec/caBundle
    kind: APIService
  - path: data/tls.crt
    kind: Secret
  - path: data/tls.key
    kind: Secret
  - path: webhooks/clientConfig/caBundle
    kind: ValidatingWebhookConfiguration
