varReference:
  - path: spec/caBundle
    kind: APIService
  - path: data/tls.crt
    kind: Secret
  - path: data/tls.key
    kind: Secret
  - path: webhooks/clientConfig/caBundle
    kind: MutatingWebhookConfiguration
